apiVersion: v1
kind: Service
metadata:
  name: pd
  namespace: beesbiz-data
spec:
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: pd
  type: ClusterIP
