apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: {{ .Values.cloudnativepgCluster.namespace }}
spec:
  instances: {{ .Values.cloudnativepgCluster.instances }}
  imageName: {{ .Values.cloudnativepgCluster.imageName }}
  imagePullPolicy: {{ .Values.cloudnativepgCluster.imagePullPolicy }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.cloudnativepgCluster.storage.size }}
    storageClass: {{ .Values.cloudnativepgCluster.storage.storageClass }}
  superuserSecret:
    name: {{ .Values.cloudnativepgCluster.superuserSecret.name }}
  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepgCluster.bootstrap.initdb.database }}
      owner: {{ .Values.cloudnativepgCluster.bootstrap.initdb.owner }}
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: {{ .Values.cloudnativepgCluster.resources.requests.cpu }}
      memory: {{ .Values.cloudnativepgCluster.resources.requests.memory }}
    limits:
      cpu: {{ .Values.cloudnativepgCluster.resources.limits.cpu }}
      memory: {{ .Values.cloudnativepgCluster.resources.limits.memory }}
