apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: {{ .Values.cloudnativepg.namespace }}
spec:
  instances: {{ .Values.cloudnativepg.instances }}
  imageName: {{ .Values.cloudnativepg.imageName }}
  imagePullPolicy: {{ .Values.cloudnativepg.imagePullPolicy }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.cloudnativepg.storage.size }}
    storageClass: {{ .Values.cloudnativepg.storage.storageClass }}
  superuserSecret:
    name: {{ .Values.cloudnativepg.superuserSecret.name }}
  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepg.bootstrap.initdb.database }}
      owner: {{ .Values.cloudnativepg.bootstrap.initdb.owner }}
  postgresql:
    parameters:
      max_connections: "1000"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: {{ .Values.cloudnativepg.resources.requests.cpu }}
      memory: {{ .Values.cloudnativepg.resources.requests.memory }}
    limits:
      cpu: {{ .Values.cloudnativepg.resources.limits.cpu }}
      memory: {{ .Values.cloudnativepg.resources.limits.memory }}
