apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.rabbitmq.namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc }}
  password: {{ .Values.rabbitmq.auth.password | b64enc }}
