apiVersion: v1
kind: Service
metadata:
  name: tikv
  labels:
    app: tikv
spec:
  ports:
    - name: http
      port: {{ .Values.tikv.port }}
      targetPort: {{ .Values.tikv.port }}
  clusterIP: None
  selector:
    app: tikv
