replicaCount:
  postgresql: 1
  tikv: 3
  pd: 3
  rabbitmq: 1

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
    ephemeralStorage: "2Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"
    ephemeralStorage: "2Gi"

postgresql:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  imagePullPolicy: IfNotPresent
  storage:
    size: 2Gi
    storageClass: "standard"
  superuserSecret:
    name: postgresql-superuser
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
  password: postgres

rabbitmq:
  adminUser: guest
  adminPassword: guest
  auth:
    username: guest
    password: guest
  image: rabbitmq:4-management
  port: 5672
  managementPort: 15672
  persistence:
    enabled: true
    size: 512Mi
    storageClass: "standard" # Adjust based on your Minikube storage class

tikv:
  image: pingcap/tikv:v5.3.0
  port: 20160
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "standard"

pd:
  image: pingcap/pd:v5.3.0
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "standard"
