namespace: beesbiz-data
clusterScoped: false

tikvCluster:
  namespace: beesbiz-tikv
  name: tikv-cluster
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3
    replicas: 3
    storageClassName: "standard"
    resources:
      requests:
        storage: "2Gi"
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"

  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 3
    replicas: 3
    storageClassName: "standard"
    resources:
      requests:
        storage: "2Gi"
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"

monitoring:
  enabled: true
  namespace: beesbiz-monitoring
  name: tikv-monitor
  prometheus:
    retention: 15d
    resources:
      requests:
        storage: "1Gi"
    storageClassName: "standard"

  grafana:
    auth:
      username: admin
      password: admin
    persistence:
      enabled: true
      size: "1Gi"
      storageClassName: "standard"
    credentials:
      secretName: basic-grafana
      secretNamespace: beesbiz-monitoring

cloudnativepgCluster:
  namespace: beesbiz-data
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  storage:
    size: 2Gi
    storageClass: "standard"
  superuserSecret:
    name: postgresql-superuser
    namespace: beesbiz-data
  bootstrap:
    initdb:
      database: postgres
      owner: postgres

rabbitmq:
  namespace: beesbiz-rabbitmq
  port: 5672
  managementPort: 15672
  replicas: 1
  image: rabbitmq:4-management
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "standard"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
      ephemeralStorage: "2Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
      ephemeralStorage: "2Gi"

  auth:
    username: rabbitmq
    password: rabbitmq
