[apiary]
name = "MainApiary"
rabbitmq_url = "amqp://guest:guest@localhost:5672/%2f"
log_level = "info"
hives = [
    { id = 1, name = "Hive1", sensors = [
        { sensor_id = 1, sensor_type = "Temperature" },
        { sensor_id = 2, sensor_type = "Humidity" }
    ]},
    { id = 2, name = "Hive2", sensors = [
        { sensor_id = 3, sensor_type = "Temperature" },
        { sensor_id = 4, sensor_type = "Pressure" }
    ]}
]
