apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tikv
  namespace: beesbiz-data
  labels:
    app: tikv
spec:
  serviceName: "tikv"
  replicas: {{ .Values.replicaCount.tikv }}
  selector:
    matchLabels:
      app: tikv
  template:
    metadata:
      labels:
        app: tikv
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - tikv
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tikv
          image: {{ .Values.tikv.image }}
          ports:
            - containerPort: {{ .Values.tikv.port }}
          args:
            - --pd=http://pd.$(NAMESPACE).svc.cluster.local:2379
            - --addr=0.0.0.0:20160
            - --advertise-addr=$(POD_NAME).tikv.$(NAMESPACE).svc.cluster.local:20160
            - --status-addr=0.0.0.0:20180
            - --advertise-status-addr=$(POD_NAME).tikv-status.$(NAMESPACE).svc.cluster.local:20180
            - --data-dir=/var/lib/tikv/data
            - --capacity=2GB
            - --config=/etc/tikv/tikv.toml
          volumeMounts:
            - name: data
              mountPath: /var/lib/tikv
            - name: config
              mountPath: /etc/tikv
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage:
                {{ .Values.resources.limits.ephemeralStorage }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage:
                {{ .Values.resources.requests.ephemeralStorage }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.tikv.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.tikv.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
      initContainers:
        - name: init-tikv
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/tikv/data/* && rm -f /var/lib/tikv/db/CURRENT']
          volumeMounts:
            - name: data
              mountPath: /var/lib/tikv
      volumes:
        - name: config
          configMap:
            name: tikv-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
