apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beesbiz-runtime
  name: beesbiz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beesbiz-server
  template:
    metadata:
      labels:
        app: beesbiz-server
    spec:
      containers:
        - name: beesbiz-server
          image: beesbiz-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.env
              subPath: config.env
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config-volume
          secret:
            secretName: config-env
