apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: beesbiz-data
  name: pv-postgresql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/postgresql"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: beesbiz-data
  name: pv-rabbitmq
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/rabbitmq"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: beesbiz-data
  name: pv-tikv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/tikv"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: beesbiz-data
  name: pv-pd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/pd"
