name: golangci-lint
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'      # Only run the action if changes are made in the src directory
  pull_request:
    paths:
      - 'src/**'      # Same for pull requests

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: src   # Set working directory to src
          args: --timeout=5m
