name: Lint Migrations

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'      # Only run the action if changes are made in the src directory
  pull_request:
    paths:
      - 'src/**'      # Same for pull requests

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbdchd/squawk-action@v2
        with:
          pattern: "migrations/*.sql"
          version: "latest"
